export const plane_data = [
  {
    name: "F-9 Cougar",
    wingspan: 34.5,
    wingarea: 300,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/b/b5/Grumman_F9F-6_in_flight_1952.JPG"
    }
  },
  {
    name: "F-11 Tiger",
    wingspan: 31.6,
    wingarea: 250,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/F11F-1_Tiger_on_USS_Forrestal_%28CVA-59%29_in_April_1956.jpg/1280px-F11F-1_Tiger_on_USS_Forrestal_%28CVA-59%29_in_April_1956.jpg"
    }
  },
  {
    name: "F-14 Tomcat",
    wingspan: 38.0,
    wingarea: 565,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/US_Navy_051105-F-5480T-005_An_F-14D_Tomcat_conducts_a_mission_over_the_Persian_Gulf-region.jpg/1280px-US_Navy_051105-F-5480T-005_An_F-14D_Tomcat_conducts_a_mission_over_the_Persian_Gulf-region.jpg"
    }
  },
  {
    name: "F-15 Eagle",
    wingspan: 42.8,
    wingarea: 608,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/F-15%2C_71st_Fighter_Squadron%2C_in_flight.JPG/1600px-F-15%2C_71st_Fighter_Squadron%2C_in_flight.JPG"
    }
  },
  {
    name: "F-16 Fighting Falcon",
    wingspan: 32.7,
    wingarea: 300,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Lockheed_Martin_F-22A_Raptor_JSOH.jpg"
    }
  },
  {
    name: "F/A-18 Hornet",
    wingspan: 40.3,
    wingarea: 410,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/4/44/FA-18C_desert_refueling.jpg"
    }
  },
  {
    name: "F-20 Tigershark",
    wingspan: 28.0,
    wingarea: 200,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/F-20_flying.jpg/1280px-F-20_flying.jpg"
    }
  },
  {
    name: "F-22 Raptor",
    wingspan: 44.5,
    wingarea: 840,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Lockheed_Martin_F-22A_Raptor_JSOH.jpg"
    }
  },
  {
    name: "YF-23 Black Widow",
    wingspan: 43.6,
    wingarea: 900,
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/2/2b/Northrop_YF-23_DFRC.jpg"
    }
  },
  {
    name: "F-35 Lightning II",
    wingspan: 35.0,
    wingarea: 460,
    /*aspectratio: wingspan^2/wingarea,*/
    description: "",
    mission: "Fighter",
    picture: {
      url:
        "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_%28cropped%29.jpg"
    }
  }
];
export const plane_data2 = [
  {
    name: "Model 1 ",
    description:
      "B&W Seaplane was made of wood with wire bracing and linen-covered. Model 1s were used for express and airmail deliveries ",
    mission: "General Aviation ",
    opYears: "1916-1919 ",
    manufacturer: "Boeing Airplane Company|The Boeing Company ",
    capacity: 2.0,
    length: 27.5,
    wingspan: 52.0,
    wingarea: 580.0,
    aspectRatio: 4.66,
    emptyWeight: 2100.0,
    payload: 0.0,
    mtow: 2800.0,
    maxMach: 0.1,
    serviceCeiling: 6500.0,
    range: 278.07,
    wingLoading: 4.83,
    thrustToWeight: 0.0,
    powerplant: "1x Hall-Scott A-5 Straight-6 piston engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_Model_1 "
  },
  {
    name: "SR-71 Blackbird ",
    description: "Spy plane ",
    mission: "Reconnaissance|Stealth ",
    opYears: " ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 2.0,
    length: 107.42,
    wingspan: 55.58,
    wingarea: 1800.0,
    aspectRatio: 1.7,
    emptyWeight: 67500.0,
    payload: 0.0,
    mtow: 172000.0,
    maxMach: 3.3,
    serviceCeiling: 85000.0,
    range: 2900.0,
    wingLoading: 84.0,
    thrustToWeight: 0.44,
    powerplant:
      "2x Pratt & Whitney J58-1 continuous-bleed afterburning turbojets ",
    popularVariants: "A-12|AF-12|YF-12 ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_SR-71_Blackbird "
  },
  {
    name: "MQ-1 Predator ",
    description: " ",
    mission: "UAV|Strike|Reconnaissance ",
    opYears: "1995- ",
    manufacturer: "General Atomics ",
    capacity: 0.0,
    length: 27.0,
    wingspan: 48.7,
    wingarea: 123.3,
    aspectRatio: 19.0,
    emptyWeight: 1130.0,
    payload: 1120.0,
    mtow: 2250.0,
    maxMach: 0.18,
    serviceCeiling: 25000.0,
    range: 675.0,
    wingLoading: 18.25,
    thrustToWeight: 0.0,
    powerplant: "1x Rotax 914F turbocharged four-cylinder engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/General_Atomics_MQ-1_Predator "
  },
  {
    name: "MQ-9 Reaper ",
    description: " ",
    mission: "UAV|HALE|Reconnaissance|Strike ",
    opYears: "2007- ",
    manufacturer: "General Atomics ",
    capacity: 0.0,
    length: 36.08,
    wingspan: 65.58,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 4901.0,
    payload: 3800.0,
    mtow: 10494.0,
    maxMach: 0.39,
    serviceCeiling: 50000.0,
    range: 1000.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x Honeywell TPE331-10 turboprop ",
    popularVariants: "Predator B ",
    sources: "https://en.wikipedia.org/wiki/General_Atomics_MQ-9_Reaper "
  },
  {
    name: "MQ-25 Stingray ",
    description:
      "Navy unmanned aerial refueling craft, wing fold for increased spot factor on deck. ",
    mission: "UAV|Reconnaissance|Stealth|Tanker ",
    opYears: "2018- ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 51.0,
    wingspan: 75.0,
    wingarea: 404.0,
    aspectRatio: 12.12,
    emptyWeight: 39500.0,
    payload: 15000.0,
    mtow: 54500.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 500.0,
    wingLoading: 134.9,
    thrustToWeight: 0.0,
    powerplant: "1x  ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "Avenger ",
    description:
      "Turbofan powered UAV with stealth features such as chines, internal weapons storage. Contains electro-optical targeting system (EOTS) also called Advanced Low-Observable Embedded Reconnaissance Targeting (ALERT) System, similar to the one used on F-35 Lightning II ",
    mission: "UAV|Strike|Reconnaissance|Stealth ",
    opYears: "2009- ",
    manufacturer: "General Atomics ",
    capacity: 0.0,
    length: 44.0,
    wingspan: 66.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 18200.0,
    maxMach: 0.61,
    serviceCeiling: 50000.0,
    range: 5400.0,
    wingLoading: 0.0,
    thrustToWeight: 0.22,
    powerplant: "1x Pratt & Whitney Canada PW545B turbofan ",
    popularVariants: "Predator C ",
    sources: "https://en.wikipedia.org/wiki/General_Atomics_Avenger "
  },
  {
    name: "ScanEagle ",
    description: " ",
    mission: "UAV|Reconnaissance ",
    opYears: "2002- ",
    manufacturer: "The Boeing Company|Insitu ",
    capacity: 0.0,
    length: 5.6,
    wingspan: 10.2,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 40.0,
    payload: 7.5,
    mtow: 48.5,
    maxMach: 0.12,
    serviceCeiling: 19500.0,
    range: 720.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x 2-stroke 3W piston engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_Insitu_ScanEagle "
  },
  {
    name: "RQ-2 ",
    description:
      "Gunnery spotting, its mission evolving into reconnaissance and surveillance, primarily for amphibious forces ",
    mission: "UAV ",
    opYears: "1986-2007 ",
    manufacturer: "AAI ",
    capacity: 0.0,
    length: 14.0,
    wingspan: 16.9,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 452.0,
    payload: 0.0,
    mtow: 452.0,
    maxMach: 0.17,
    serviceCeiling: 15000.0,
    range: 100.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x Sachs 2-stroke 2-cylinder engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/AAI_RQ-2_Pioneer "
  },
  {
    name: "RQ-4 Global Hawk ",
    description:
      "High resolution SAR, EO/IR; can survey as much as 40,000 sq mi of terrain a day. ",
    mission: "UAV|Reconnaissance ",
    opYears: "1998- ",
    manufacturer: "Northrop Grumman ",
    capacity: 0.0,
    length: 47.6,
    wingspan: 130.9,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 14950.0,
    payload: 17300.0,
    mtow: 32250.0,
    maxMach: 0.51,
    serviceCeiling: 60000.0,
    range: 12299.0,
    wingLoading: 0.0,
    thrustToWeight: 0.24,
    powerplant: "1x Rolls-Royce F137-RR-100 turbofan ",
    popularVariants: "MQ-4C Triton ",
    sources: "https://en.wikipedia.org/wiki/Northrop_Grumman_RQ-4_Global_Hawk "
  },
  {
    name: "RQ-7 ",
    description: "Tactical reconnaissance UAS for ground maneuver forces ",
    mission: "UAV ",
    opYears: "1991-2002 ",
    manufacturer: "AAI ",
    capacity: 0.0,
    length: 11.2,
    wingspan: 14.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 186.0,
    payload: 0.0,
    mtow: 375.0,
    maxMach: 0.17,
    serviceCeiling: 15000.0,
    range: 59.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x Wankel UAV engine 741 ",
    popularVariants: "RQ-7A|RQ-7B ",
    sources: "https://en.wikipedia.org/wiki/AAI_RQ-7_Shadow "
  },
  {
    name: "RQ-21 Blackjack ",
    description:
      "Formerly called the Integrator, this UAV was designed and built by Boeing Insitu for the USN requirement for a Small Tactical Unmanned Air System (STUAS). Supplemental to the Boeing Insitu ScanEagle ",
    mission: "UAV|Reconnaissance ",
    opYears: "2014- ",
    manufacturer: "The Boeing Company|Insitu ",
    capacity: 0.0,
    length: 8.2,
    wingspan: 16.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 81.0,
    payload: 54.0,
    mtow: 135.0,
    maxMach: 0.11,
    serviceCeiling: 19500.0,
    range: 50.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x EFI piston engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_Insitu_RQ-21_Blackjack "
  },
  {
    name: "RQ-170 Sentinel ",
    description: " ",
    mission: "UAV|Reconnaissance ",
    opYears: "2007- ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 14.75,
    wingspan: 65.58,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 50000.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "1x Garrett TFE731|or 1x General Electric TF34 turbofan ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_Martin_RQ-170_Sentinel "
  },
  {
    name: "FH Phantom ",
    description: " ",
    mission: "Fighter ",
    opYears: "1947-1954 ",
    manufacturer: "McDonnell|The Boeing Company ",
    capacity: 1.0,
    length: 37.25,
    wingspan: 40.75,
    wingarea: 276.0,
    aspectRatio: 6.02,
    emptyWeight: 6683.0,
    payload: 3352.0,
    mtow: 12035.0,
    maxMach: 0.63,
    serviceCeiling: 41100.0,
    range: 604.0,
    wingLoading: 36.4,
    thrustToWeight: 0.32,
    powerplant: "2x Westinghouse J30-WE-20 turbojets ",
    popularVariants: "FH-1 ",
    sources:
      "https://en.wikipedia.org/wiki/McDonnell_FH_Phantom#Specifications_(FH-1_Phantom) "
  },
  {
    name: "F2H Banshee ",
    description: " ",
    mission: "Fighter ",
    opYears: "1948-1962 ",
    manufacturer: "McDonnell|The Boeing Company ",
    capacity: 1.0,
    length: 48.17,
    wingspan: 41.75,
    wingarea: 294.0,
    aspectRatio: 5.93,
    emptyWeight: 13183.0,
    payload: 7830.0,
    mtow: 25214.0,
    maxMach: 0.76,
    serviceCeiling: 46600.0,
    range: 1492.0,
    wingLoading: 85.76,
    thrustToWeight: 0.0,
    powerplant: "2x Westinghouse J34-WE-34 turbojets ",
    popularVariants: "F2H-3 ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_F2H_Banshee "
  },
  {
    name: "F3H Demon ",
    description: " ",
    mission: "Fighter ",
    opYears: "1956-1964 ",
    manufacturer: "McDonnell|The Boeing Company ",
    capacity: 1.0,
    length: 59.0,
    wingspan: 35.33,
    wingarea: 519.0,
    aspectRatio: 2.41,
    emptyWeight: 21133.0,
    payload: 0.0,
    mtow: 33900.0,
    maxMach: 0.94,
    serviceCeiling: 35050.0,
    range: 1191.0,
    wingLoading: 65.32,
    thrustToWeight: 0.29,
    powerplant: "1x Allison J71-A-2E turbojet ",
    popularVariants: "F3H-2 ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_F3H_Demon "
  },
  {
    name: "F4H/F-4/F-110 Phantom II ",
    description: " ",
    mission: "Fighter ",
    opYears: "1960-2016 ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 2.0,
    length: 63.0,
    wingspan: 38.42,
    wingarea: 530.0,
    aspectRatio: 2.77,
    emptyWeight: 30328.0,
    payload: 11172.0,
    mtow: 61795.0,
    maxMach: 2.23,
    serviceCeiling: 60000.0,
    range: 367.0,
    wingLoading: 78.0,
    thrustToWeight: 0.86,
    powerplant: "2x General Electric J79-GE-17A afterburning turbojets ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_F-4_Phantom_II "
  },
  {
    name: "F-5 ",
    description: " ",
    mission: "Fighter ",
    opYears: "1959- ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 1.0,
    length: 47.4,
    wingspan: 26.67,
    wingarea: 186.0,
    aspectRatio: 3.82,
    emptyWeight: 9558.0,
    payload: 6187.0,
    mtow: 24722.0,
    maxMach: 1.6,
    serviceCeiling: 51800.0,
    range: 760.0,
    wingLoading: 132.91,
    thrustToWeight: 0.28,
    powerplant: "2x General Electric J85-GE-21B turbojets ",
    popularVariants: "F-5A/B Freedom Fighter|F-5E/F Tiger II ",
    sources: "https://en.wikipedia.org/wiki/Northrop_F-5 "
  },
  {
    name: "F-9 Cougar ",
    description: " ",
    mission: "Fighter ",
    opYears: "1952-1974 ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 1.0,
    length: 40.92,
    wingspan: 34.5,
    wingarea: 300.0,
    aspectRatio: 3.97,
    emptyWeight: 11483.0,
    payload: 4761.0,
    mtow: 21000.0,
    maxMach: 0.86,
    serviceCeiling: 44500.0,
    range: 810.0,
    wingLoading: 61.0,
    thrustToWeight: 0.35,
    powerplant: "1x Pratt & Whitney J48-P-8A turbojet ",
    popularVariants: "F9F-6|F-9F ",
    sources: "https://en.wikipedia.org/wiki/Grumman_F-9_Cougar "
  },
  {
    name: "F-11 Tiger ",
    description: " ",
    mission: "Fighter ",
    opYears: "1956-1969 ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 1.0,
    length: 46.92,
    wingspan: 31.63,
    wingarea: 250.0,
    aspectRatio: 4.0,
    emptyWeight: 13810.0,
    payload: 7225.0,
    mtow: 23459.0,
    maxMach: 1.1,
    serviceCeiling: 49000.0,
    range: 1110.0,
    wingLoading: 84.0,
    thrustToWeight: 0.5,
    powerplant: "1x Wright J65-W-18 turbojet ",
    popularVariants: "F11F-1|F-11A ",
    sources: "https://en.wikipedia.org/wiki/Grumman_F-11_Tiger "
  },
  {
    name: "F-14 Tomcat ",
    description:
      "Fighter with variable sweep to accommodate different flight profiles and missions.|The spread configuration has a 64 ft wingspan and an effective 1008 ft2 wing area ",
    mission: "Fighter ",
    opYears: "1974-2006 ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 2.0,
    length: 62.75,
    wingspan: 38.0,
    wingarea: 565.0,
    aspectRatio: 2.56,
    emptyWeight: 43735.0,
    payload: 17265.0,
    mtow: 74350.0,
    maxMach: 2.34,
    serviceCeiling: 50000.0,
    range: 500.0,
    wingLoading: 96.0,
    thrustToWeight: 0.88,
    powerplant: "2x General Electric F110-GE-400 afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Grumman_F-14_Tomcat "
  },
  {
    name: "F-15 Eagle ",
    description: "USAF Air Superiority fighter ",
    mission: "Fighter ",
    opYears: "1976- ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 1.0,
    length: 63.75,
    wingspan: 42.83,
    wingarea: 608.0,
    aspectRatio: 3.02,
    emptyWeight: 28000.0,
    payload: 0.0,
    mtow: 68000.0,
    maxMach: 2.5,
    serviceCeiling: 65000.0,
    range: 1061.0,
    wingLoading: 73.1,
    thrustToWeight: 1.07,
    powerplant: "2x Pratt & Whitney F100-PW-100/-200 afterburning turbofans ",
    popularVariants: "F-15C/E/F|F-15SA/SR|F-15SG|F-15I|F-15T|F-15J|F-15QA ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_F-15_Eagle "
  },
  {
    name: "F-16 Fighting Falcon ",
    description: " ",
    mission: "Fighter ",
    opYears: "1978- ",
    manufacturer: "General Dynamics|Lockheed Martin ",
    capacity: 1.0,
    length: 49.42,
    wingspan: 32.67,
    wingarea: 300.0,
    aspectRatio: 3.56,
    emptyWeight: 18900.0,
    payload: 7600.0,
    mtow: 42300.0,
    maxMach: 2.0,
    serviceCeiling: 50000.0,
    range: 295.0,
    wingLoading: 88.3,
    thrustToWeight: 1.1,
    powerplant:
      "1x General Electric F110-GE-129 afterburning turbofan|or 1x Pratt & Whitney F100-PW-200/-200E afterburning turbofan ",
    popularVariants: "F-16C ",
    sources:
      "https://en.wikipedia.org/wiki/General_Dynamics_F-16_Fighting_Falcon "
  },
  {
    name: "F/A-18 Hornet ",
    description:
      "Versatile Navy fighter. Wings fold for reduced spot factor on deck.|C and E models have one pilot, D and F models have 2 ",
    mission: "Fighter|Attack ",
    opYears: "1983- ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 2.0,
    length: 56.08,
    wingspan: 40.33,
    wingarea: 410.0,
    aspectRatio: 4.0,
    emptyWeight: 23000.0,
    payload: 13970.0,
    mtow: 51900.0,
    maxMach: 1.8,
    serviceCeiling: 50000.0,
    range: 1089.0,
    wingLoading: 93.0,
    thrustToWeight: 0.96,
    powerplant: "2x General Electric F404-GE-402 afterburning turbofans ",
    popularVariants: "F/A-18C|F/A-18D ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_F/A-18_Hornet "
  },
  {
    name: "F-20 Tigershark ",
    description: " ",
    mission: "Fighter ",
    opYears: "1982 ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 1.0,
    length: 47.33,
    wingspan: 27.99,
    wingarea: 200.0,
    aspectRatio: 3.92,
    emptyWeight: 13150.0,
    payload: 2330.0,
    mtow: 27500.0,
    maxMach: 2.0,
    serviceCeiling: 55000.0,
    range: 300.0,
    wingLoading: 81.0,
    thrustToWeight: 1.1,
    powerplant: "1x General Electric F404-GE-100 turbofan ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Northrop_F-20_Tigershark "
  },
  {
    name: "F-22 Raptor ",
    description: " ",
    mission: "Fighter ",
    opYears: "2005- ",
    manufacturer: "Lockheed Martin ",
    capacity: 1.0,
    length: 62.08,
    wingspan: 44.5,
    wingarea: 840.0,
    aspectRatio: 2.36,
    emptyWeight: 43340.0,
    payload: 21500.0,
    mtow: 83500.0,
    maxMach: 2.25,
    serviceCeiling: 65000.0,
    range: 460.0,
    wingLoading: 77.2,
    thrustToWeight: 1.08,
    powerplant:
      "2x Pratt & Whitney F119-PW-100 afterburning, thrust vectoring turbofans ",
    popularVariants: "F-22A ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_Martin_F-22_Raptor "
  },
  {
    name: "YF-23 ",
    description: " ",
    mission: "Fighter|Experimental ",
    opYears: "1990 ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 1.0,
    length: 67.42,
    wingspan: 43.58,
    wingarea: 900.0,
    aspectRatio: 2.11,
    emptyWeight: 29000.0,
    payload: 22320.0,
    mtow: 51320.0,
    maxMach: 2.2,
    serviceCeiling: 65000.0,
    range: 775.0,
    wingLoading: 54.0,
    thrustToWeight: 1.36,
    powerplant:
      "2x Pratt & Whitney YF119 afterburning turbofans|or 2x General Electric YF120 afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Northrop_YF-23 "
  },
  {
    name: "F-35 Lightning II ",
    description: " ",
    mission: "Fighter ",
    opYears: "2015- ",
    manufacturer: "Lockheed Martin ",
    capacity: 1.0,
    length: 50.5,
    wingspan: 35.0,
    wingarea: 460.0,
    aspectRatio: 2.66,
    emptyWeight: 28999.0,
    payload: 20442.0,
    mtow: 70000.0,
    maxMach: 1.61,
    serviceCeiling: 50000.0,
    range: 669.0,
    wingLoading: 107.5,
    thrustToWeight: 0.87,
    powerplant: "1x Pratt & Whitney F135 afterburning turbofan ",
    popularVariants: "F-35A ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_Martin_F-35_Lightning_II "
  },
  {
    name: "F-100 Super Sabre ",
    description: " ",
    mission: "Fighter ",
    opYears: "1954-1988 ",
    manufacturer: "North American ",
    capacity: 1.0,
    length: 50.0,
    wingspan: 38.75,
    wingarea: 400.0,
    aspectRatio: 3.76,
    emptyWeight: 21000.0,
    payload: 7847.0,
    mtow: 34832.0,
    maxMach: 1.3,
    serviceCeiling: 50000.0,
    range: 1733.0,
    wingLoading: 72.1,
    thrustToWeight: 0.55,
    powerplant: "1x Pratt & Whitney J57-P-21/21A turbojet ",
    popularVariants: "F-100D ",
    sources: "https://en.wikipedia.org/wiki/North_American_F-100_Super_Sabre "
  },
  {
    name: "F-101 Voodoo ",
    description: " ",
    mission: "Fighter ",
    opYears: "1954-1984 ",
    manufacturer: "McDonnell|The Boeing Company ",
    capacity: 2.0,
    length: 67.42,
    wingspan: 39.67,
    wingarea: 368.0,
    aspectRatio: 4.28,
    emptyWeight: 28495.0,
    payload: 17170.0,
    mtow: 52400.0,
    maxMach: 1.72,
    serviceCeiling: 58400.0,
    range: 1320.0,
    wingLoading: 124.0,
    thrustToWeight: 0.74,
    powerplant: "2x Pratt & Whitney J57-P-55 afterburning turbojets ",
    popularVariants: "F-101B ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_F-101_Voodoo "
  },
  {
    name: "F-102 Delta Dagger ",
    description: " ",
    mission: "Fighter ",
    opYears: "1956-1979 ",
    manufacturer: "Convair ",
    capacity: 1.0,
    length: 68.33,
    wingspan: 38.08,
    wingarea: 695.0,
    aspectRatio: 2.09,
    emptyWeight: 19350.0,
    payload: 5150.0,
    mtow: 31500.0,
    maxMach: 1.25,
    serviceCeiling: 53400.0,
    range: 1170.0,
    wingLoading: 35.0,
    thrustToWeight: 0.7,
    powerplant: "1x Pratt & Whitney J57-P-25 afterburning turbojet ",
    popularVariants: "F-102A ",
    sources: "https://en.wikipedia.org/wiki/Convair_F-102_Delta_Dagger "
  },
  {
    name: "F-104 Starfighter ",
    description: " ",
    mission: "Fighter ",
    opYears: "1958-2004 ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 1.0,
    length: 54.67,
    wingspan: 21.75,
    wingarea: 196.1,
    aspectRatio: 2.41,
    emptyWeight: 14000.0,
    payload: 15027.0,
    mtow: 29027.0,
    maxMach: 2.0,
    serviceCeiling: 50000.0,
    range: 365.0,
    wingLoading: 105.0,
    thrustToWeight: 0.54,
    powerplant: "1x General Electric J79 afterburning turbojet ",
    popularVariants: "F-104G ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_F-104_Starfighter "
  },
  {
    name: "F-106 Delta Dart ",
    description: " ",
    mission: "Fighter ",
    opYears: "1959-1998 ",
    manufacturer: "Convair ",
    capacity: 1.0,
    length: 70.7,
    wingspan: 38.25,
    wingarea: 695.0,
    aspectRatio: 2.1,
    emptyWeight: 24420.0,
    payload: 10090.0,
    mtow: 34510.0,
    maxMach: 2.3,
    serviceCeiling: 57000.0,
    range: 500.0,
    wingLoading: 52.0,
    thrustToWeight: 0.71,
    powerplant: "1x Pratt & Whitney J75-17 afterburning turbojet ",
    popularVariants: "F-106A ",
    sources: "https://en.wikipedia.org/wiki/Convair_F-106_Delta_Dart "
  },
  {
    name: "F-111 Aardvark ",
    description:
      "Fighter with variable sweep to accommodate different flight profiles and missions.|The spread configuration has a 63 ft wingspan and an effective 657.4 ft2 wing area ",
    mission: "Fighter ",
    opYears: "1967-2010 ",
    manufacturer: "General Dynamics ",
    capacity: 2.0,
    length: 73.5,
    wingspan: 32.0,
    wingarea: 525.0,
    aspectRatio: 1.95,
    emptyWeight: 47200.0,
    payload: 35600.0,
    mtow: 100000.0,
    maxMach: 2.5,
    serviceCeiling: 66000.0,
    range: 3210.0,
    wingLoading: 158.0,
    thrustToWeight: 0.61,
    powerplant: "2x Pratt & Whitney TF30-P-100 turbofans ",
    popularVariants: "F-111F ",
    sources: "https://en.wikipedia.org/wiki/General_Dynamics_F-111_Aardvark "
  },
  {
    name: "F-117 Nighthawk ",
    description: " ",
    mission: "Fighter|Stealth ",
    opYears: "1983-2008 ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 1.0,
    length: 65.92,
    wingspan: 43.33,
    wingarea: 780.0,
    aspectRatio: 2.41,
    emptyWeight: 29500.0,
    payload: 23000.0,
    mtow: 52500.0,
    maxMach: 0.92,
    serviceCeiling: 45000.0,
    range: 930.0,
    wingLoading: 67.3,
    thrustToWeight: 0.4,
    powerplant: "2x General Electric F404-F1D2 turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_F-117_Nighthawk "
  },
  {
    name: "Su-27 ",
    description: "Russian ",
    mission: "Fighter ",
    opYears: "1985- ",
    manufacturer: "Sukhoi ",
    capacity: 1.0,
    length: 72.0,
    wingspan: 48.25,
    wingarea: 667.0,
    aspectRatio: 3.49,
    emptyWeight: 36100.0,
    payload: 15550.0,
    mtow: 67100.0,
    maxMach: 2.35,
    serviceCeiling: 62523.0,
    range: 1906.0,
    wingLoading: 91.06,
    thrustToWeight: 0.91,
    powerplant: "2x Saturn AL-31F turbofans ",
    popularVariants: "Su-27SK ",
    sources: "https://en.wikipedia.org/wiki/Sukhoi_Su-27 "
  },
  {
    name: "Su-35 ",
    description: "Russian ",
    mission: "Fighter ",
    opYears: "2014- ",
    manufacturer: "Sukhoi ",
    capacity: 1.0,
    length: 72.92,
    wingspan: 50.17,
    wingarea: 667.0,
    aspectRatio: 3.77,
    emptyWeight: 37920.0,
    payload: 18740.0,
    mtow: 76060.0,
    maxMach: 2.25,
    serviceCeiling: 59100.0,
    range: 1940.0,
    wingLoading: 102.57,
    thrustToWeight: 0.92,
    powerplant: "2x Saturn AL-41F1S afterburning turbofans ",
    popularVariants: "Su-27M|Su-35S ",
    sources: "https://en.wikipedia.org/wiki/Sukhoi_Su-35 "
  },
  {
    name: "Su-47 Berkut ",
    description: "Russian. Canceled ",
    mission: "Fighter ",
    opYears: "1997 ",
    manufacturer: "Sukhoi ",
    capacity: 1.0,
    length: 74.17,
    wingspan: 54.75,
    wingarea: 666.0,
    aspectRatio: 4.5,
    emptyWeight: 36100.0,
    payload: 19015.0,
    mtow: 77162.0,
    maxMach: 1.65,
    serviceCeiling: 59050.0,
    range: 2050.0,
    wingLoading: 79.4,
    thrustToWeight: 1.16,
    powerplant:
      "2x Aviadvigatel D-30F11 afterburning, thrust vectoring turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Sukhoi_Su-47 "
  },
  {
    name: "Su-57 ",
    description: "Russian ",
    mission: "Fighter ",
    opYears: "2009- ",
    manufacturer: "Sukhoi ",
    capacity: 1.0,
    length: 65.0,
    wingspan: 45.83,
    wingarea: 848.1,
    aspectRatio: 2.48,
    emptyWeight: 39680.0,
    payload: 15435.0,
    mtow: 77160.0,
    maxMach: 2.0,
    serviceCeiling: 65000.0,
    range: 1890.0,
    wingLoading: 91.0,
    thrustToWeight: 1.36,
    powerplant: "2x izdeliye 30 turbofans ",
    popularVariants: "T-50 ",
    sources: "https://en.wikipedia.org/wiki/Sukhoi_Su-57 "
  },
  {
    name: "J-20 Black Dragon ",
    description: "Chinese ",
    mission: "Fighter ",
    opYears: "2017- ",
    manufacturer: "Chengdu ",
    capacity: 1.0,
    length: 66.8,
    wingspan: 44.2,
    wingarea: 840.0,
    aspectRatio: 2.33,
    emptyWeight: 42750.0,
    payload: 28000.0,
    mtow: 80001.0,
    maxMach: 1.72,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 84.0,
    thrustToWeight: 1.06,
    powerplant: "2x Shenyang WS-10G afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Chengdu_J-20 "
  },
  {
    name: "J-31 ",
    description: "Chinese ",
    mission: "Fighter ",
    opYears: "2019- ",
    manufacturer: "Shenyang ",
    capacity: 1.0,
    length: 56.75,
    wingspan: 37.75,
    wingarea: 430.0,
    aspectRatio: 3.31,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 1.8,
    serviceCeiling: 0.0,
    range: 675.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "2x RD-93 afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Shenyang_J-31 "
  },
  {
    name: "Typhoon ",
    description: "European twin-engine, canard-delta wing, multirole fighter ",
    mission: "Fighter ",
    opYears: "2003- ",
    manufacturer: "Eurofighter GmbH|Airbus|BAE Systems|Leonardo ",
    capacity: 1.0,
    length: 52.4,
    wingspan: 35.9,
    wingarea: 551.0,
    aspectRatio: 2.34,
    emptyWeight: 24000.0,
    payload: 11270.0,
    mtow: 51800.0,
    maxMach: 2.0,
    serviceCeiling: 65000.0,
    range: 1564.16,
    wingLoading: 63.9,
    thrustToWeight: 1.15,
    powerplant: "2x Eurojet EJ200 afterburning turbofan ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Eurofighter_Typhoon "
  },
  {
    name: "Rafale ",
    description: "French ",
    mission: "Fighter ",
    opYears: "2001- ",
    manufacturer: "Dassault Aviation ",
    capacity: 1.0,
    length: 50.1,
    wingspan: 35.4,
    wingarea: 492.0,
    aspectRatio: 2.55,
    emptyWeight: 23400.0,
    payload: 9600.0,
    mtow: 54000.0,
    maxMach: 1.8,
    serviceCeiling: 50000.0,
    range: 2000.0,
    wingLoading: 67.1,
    thrustToWeight: 0.99,
    powerplant: "2x Snecma M88-2 turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Dassault_Rafale "
  },
  {
    name: "JAS 39 Gripen ",
    description: "Swedish ",
    mission: "Fighter ",
    opYears: "1997- ",
    manufacturer: "Saab Group ",
    capacity: 1.0,
    length: 46.25,
    wingspan: 27.58,
    wingarea: 323.0,
    aspectRatio: 2.36,
    emptyWeight: 14990.0,
    payload: 3710.0,
    mtow: 31000.0,
    maxMach: 2.0,
    serviceCeiling: 50000.0,
    range: 432.0,
    wingLoading: 58.0,
    thrustToWeight: 0.97,
    powerplant: "1x Volvo RM12 afterburning turbofan ",
    popularVariants: "JAS 39C|JAS 39D ",
    sources: "https://en.wikipedia.org/wiki/Saab_JAS_39_Gripen "
  },
  {
    name: "MiG-29K ",
    description: "Russian ",
    mission: "Fighter ",
    opYears: "2010- ",
    manufacturer: "Mikoyan ",
    capacity: 1.0,
    length: 57.75,
    wingspan: 39.42,
    wingarea: 462.0,
    aspectRatio: 3.36,
    emptyWeight: 24250.0,
    payload: 16650.0,
    mtow: 54000.0,
    maxMach: 2.0,
    serviceCeiling: 57400.0,
    range: 459.0,
    wingLoading: 90.5,
    thrustToWeight: 0.97,
    powerplant: "2x Klimov RD-33MK afterburning turbofans ",
    popularVariants: "Fulcrum-D ",
    sources: "https://en.wikipedia.org/wiki/Mikoyan_MiG-29K "
  },
  {
    name: "B-1 Lancer ",
    description:
      "Variable sweep bomber.|The spread configuration has a 137 ft wingspan ",
    mission: "Bomber ",
    opYears: "1974- ",
    manufacturer: "Rockwell|The Boeing Company ",
    capacity: 4.0,
    length: 146.0,
    wingspan: 79.0,
    wingarea: 1950.0,
    aspectRatio: 3.2,
    emptyWeight: 192000.0,
    payload: 125000.0,
    mtow: 477000.0,
    maxMach: 1.25,
    serviceCeiling: 60000.0,
    range: 5100.0,
    wingLoading: 167.0,
    thrustToWeight: 0.28,
    powerplant: "4x General Electric F101-GE-102 augmented turbofans ",
    popularVariants: "B-1A|B-1B ",
    sources: "https://en.wikipedia.org/wiki/Rockwell_B-1_Lancer "
  },
  {
    name: "B-2 Spirit ",
    description: " ",
    mission: "Bomber ",
    opYears: "1989- ",
    manufacturer: "Northrop Grumman ",
    capacity: 2.0,
    length: 69.0,
    wingspan: 172.0,
    wingarea: 5140.0,
    aspectRatio: 5.76,
    emptyWeight: 158000.0,
    payload: 178500.0,
    mtow: 376000.0,
    maxMach: 0.95,
    serviceCeiling: 50000.0,
    range: 6000.0,
    wingLoading: 67.3,
    thrustToWeight: 0.2,
    powerplant: "4x General Electric F118-GE-100 non-afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Northrop_Grumman_B-2_Spirit "
  },
  {
    name: "B-3 ",
    description: " ",
    mission: "Bomber ",
    opYears: "early 1920s-late 1940s ",
    manufacturer: "Keystone ",
    capacity: 5.0,
    length: 48.83,
    wingspan: 74.67,
    wingarea: 1145.0,
    aspectRatio: 4.87,
    emptyWeight: 7705.0,
    payload: 5247.0,
    mtow: 12952.0,
    maxMach: 0.15,
    serviceCeiling: 12700.0,
    range: 760.0,
    wingLoading: 11.31,
    thrustToWeight: 0.0,
    powerplant: "2x Pratt & Whitney R-1690-3 radial engines ",
    popularVariants: "B-4|B-5|B-6 ",
    sources: "https://en.wikipedia.org/wiki/Keystone_B-3 "
  },
  {
    name: "B-17 Flying Fortress ",
    description: " ",
    mission: "Bomber ",
    opYears: "1938-1968 ",
    manufacturer: "The Boeing Company ",
    capacity: 10.0,
    length: 74.33,
    wingspan: 103.75,
    wingarea: 1420.0,
    aspectRatio: 7.57,
    emptyWeight: 34135.0,
    payload: 19865.0,
    mtow: 65500.0,
    maxMach: 0.38,
    serviceCeiling: 35600.0,
    range: 1738.0,
    wingLoading: 38.0,
    thrustToWeight: 0.0,
    powerplant: "4x Wright R-1820-97 Cyclone turbosupercharged radial engines ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_B-17_Flying_Fortress "
  },
  {
    name: "B-21 Raider ",
    description: " ",
    mission: "Bomber ",
    opYears: "In development ",
    manufacturer: "Northrop Grumman ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "B-24 Liberator ",
    description: " ",
    mission: "Bomber ",
    opYears: " ",
    manufacturer: " ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "B-25 Mitchell ",
    description: " ",
    mission: "Bomber ",
    opYears: " ",
    manufacturer: " ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "B-26 Marauder ",
    description: " ",
    mission: "Bomber ",
    opYears: " ",
    manufacturer: "Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "B-29 Superfortress ",
    description: " ",
    mission: "Bomber ",
    opYears: "1994-1960 ",
    manufacturer: "The Boeing Company ",
    capacity: 11.0,
    length: 99.0,
    wingspan: 141.25,
    wingarea: 1736.0,
    aspectRatio: 11.5,
    emptyWeight: 74500.0,
    payload: 45500.0,
    mtow: 135000.0,
    maxMach: 0.47,
    serviceCeiling: 31850.0,
    range: 2820.0,
    wingLoading: 69.12,
    thrustToWeight: 0.0,
    powerplant:
      "4x Wright R-335023 Duplex-Cyclone turbosupercharged radial engines ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_B-29_Superfortress "
  },
  {
    name: "B-36 Peacemaker ",
    description: " ",
    mission: "Bomber ",
    opYears: "1946-1959 ",
    manufacturer: "Convair ",
    capacity: 13.0,
    length: 162.08,
    wingspan: 230.0,
    wingarea: 4772.0,
    aspectRatio: 11.09,
    emptyWeight: 166165.0,
    payload: 96335.0,
    mtow: 410000.0,
    maxMach: 0.55,
    serviceCeiling: 43600.0,
    range: 3465.0,
    wingLoading: 85.92,
    thrustToWeight: 0.0,
    powerplant:
      "6x Pratt & Whitney R-4360-53 radial engines|and 4x General Electric J47 turbojets ",
    popularVariants: "X-6 ",
    sources: "https://en.wikipedia.org/wiki/Convair_B-36_Peacemaker "
  },
  {
    name: "B-50 Superfortress ",
    description: " ",
    mission: "Bomber ",
    opYears: "1948-1965 ",
    manufacturer: "The Boeing Company ",
    capacity: 10.0,
    length: 99.0,
    wingspan: 141.25,
    wingarea: 1720.0,
    aspectRatio: 11.6,
    emptyWeight: 84714.0,
    payload: 37136.0,
    mtow: 173000.0,
    maxMach: 0.52,
    serviceCeiling: 36900.0,
    range: 2080.0,
    wingLoading: 70.19,
    thrustToWeight: 0.0,
    powerplant:
      "4x Pratt & Whitney R-4340-35 28 cylinder four-row air-cooled radial piston engine|or 2x General Electric J47-GE-23 turbojets ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_B-50_Superfortress "
  },
  {
    name: "B-52 Stratofortress ",
    description: "Nickname BUFF ",
    mission: "Bomber ",
    opYears: "1955- ",
    manufacturer: "The Boeing Company ",
    capacity: 5.0,
    length: 159.33,
    wingspan: 185.0,
    wingarea: 4000.0,
    aspectRatio: 8.56,
    emptyWeight: 185000.0,
    payload: 80000.0,
    mtow: 488000.0,
    maxMach: 0.85,
    serviceCeiling: 50000.0,
    range: 3890.0,
    wingLoading: 120.0,
    thrustToWeight: 0.31,
    powerplant: "8x Pratt & Whitney TF33-P-3/103 turbofans ",
    popularVariants: "B-52H ",
    sources: "https://en.wikipedia.org/wiki/Boeing_B-52_Stratofortress "
  },
  {
    name: "B-58 Hustler ",
    description: " ",
    mission: "Bomber ",
    opYears: "1956-1970 ",
    manufacturer: "Convair ",
    capacity: 3.0,
    length: 96.83,
    wingspan: 56.75,
    wingarea: 1542.0,
    aspectRatio: 2.09,
    emptyWeight: 55560.0,
    payload: 12311.0,
    mtow: 176890.0,
    maxMach: 2.0,
    serviceCeiling: 63400.0,
    range: 1510.0,
    wingLoading: 44.0,
    thrustToWeight: 0.92,
    powerplant: "4x General Electric J79-GE-5A turbojet ",
    popularVariants: "B-58A ",
    sources: "https://en.wikipedia.org/wiki/Convair_B-58_Hustler "
  },
  {
    name: "Vulcan ",
    description: " ",
    mission: "Bomber ",
    opYears: "1956-1965 ",
    manufacturer: "Avro|Hawker Siddeley ",
    capacity: 5.0,
    length: 97.08,
    wingspan: 99.42,
    wingarea: 3554.0,
    aspectRatio: 2.78,
    emptyWeight: 83573.0,
    payload: 21000.0,
    mtow: 170000.0,
    maxMach: 0.96,
    serviceCeiling: 55000.0,
    range: 2265.0,
    wingLoading: 47.83,
    thrustToWeight: 0.31,
    powerplant: "4x Bristol Olympus Mk. 101/2/4 twin-spool turbojet engines ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Avro_Vulcan "
  },
  {
    name: "XB-70 Valkyrie ",
    description: " ",
    mission: "Bomber|Experimental ",
    opYears: "1964-1969 ",
    manufacturer: "North American Aviation|The Boeing Company ",
    capacity: 2.0,
    length: 189.0,
    wingspan: 105.0,
    wingarea: 6297.0,
    aspectRatio: 1.75,
    emptyWeight: 253600.0,
    payload: 50000.0,
    mtow: 542000.0,
    maxMach: 3.1,
    serviceCeiling: 77350.0,
    range: 3725.0,
    wingLoading: 84.93,
    thrustToWeight: 0.31,
    powerplant: "6x General Electric YJ93-GE-3 afterburning turbojet ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/North_American_XB-70_Valkyrie "
  },
  {
    name: "TBF/TBM Avenger ",
    description:
      'TBF was the original design by Grumman. TBM is the variant built by General Motors. This Navy craft has a very interesting wingfold design termed the "Grumman Fold". ',
    mission: "Bomber ",
    opYears: "1941-1960s ",
    manufacturer: "Northrop|Northrop Grumman|General Motors ",
    capacity: 3.0,
    length: 40.96,
    wingspan: 54.17,
    wingarea: 490.02,
    aspectRatio: 5.99,
    emptyWeight: 10545.0,
    payload: 7348.0,
    mtow: 17893.0,
    maxMach: 0.36,
    serviceCeiling: 30100.0,
    range: 868.98,
    wingLoading: 36.5,
    thrustToWeight: 0.0,
    powerplant: "1x Wright R-2600-20 Twin Cyclone radial engine ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Grumman_TBF_Avenger "
  },
  {
    name: "T-38 Talon ",
    description: " ",
    mission: "Trainer ",
    opYears: "1961- ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 2.0,
    length: 46.38,
    wingspan: 25.25,
    wingarea: 170.0,
    aspectRatio: 3.75,
    emptyWeight: 7200.0,
    payload: 4620.0,
    mtow: 12093.0,
    maxMach: 1.3,
    serviceCeiling: 50000.0,
    range: 991.0,
    wingLoading: 69.53,
    thrustToWeight: 0.65,
    powerplant: "2x General Electric J85-5A afterburning turbojets ",
    popularVariants: "T-38A ",
    sources: "https://en.wikipedia.org/wiki/Northrop_T-38_Talon "
  },
  {
    name: "T-45 Goshawk ",
    description: " ",
    mission: "Trainer ",
    opYears: "1991- ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 2.0,
    length: 39.33,
    wingspan: 30.83,
    wingarea: 190.1,
    aspectRatio: 5.0,
    emptyWeight: 10403.0,
    payload: 3678.0,
    mtow: 14081.0,
    maxMach: 0.85,
    serviceCeiling: 42500.0,
    range: 700.0,
    wingLoading: 74.07,
    thrustToWeight: 0.39,
    powerplant: "1x Rolls-Royce Turbomeca F405-RR-401 turbofan ",
    popularVariants: "T-45A ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_T-45_Goshawk "
  },
  {
    name: "T-X ",
    description: " ",
    mission: "Trainer ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 2.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: " ",
    sources: "NO INFO "
  },
  {
    name: "P-38 Lightning ",
    description: " ",
    mission: "Patrol|Fighter ",
    opYears: "1941-1965 ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 1.0,
    length: 37.83,
    wingspan: 52.0,
    wingarea: 327.5,
    aspectRatio: 8.26,
    emptyWeight: 12800.0,
    payload: 4700.0,
    mtow: 21600.0,
    maxMach: 0.54,
    serviceCeiling: 44000.0,
    range: 1130.0,
    wingLoading: 53.4,
    thrustToWeight: 0.0,
    powerplant: "2x Allison V-1710-111/113 V-12 piston engine ",
    popularVariants: "P-38L ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_P-38_Lightning "
  },
  {
    name: "P-51 Mustang ",
    description: " ",
    mission: "Patrol|Fighter ",
    opYears: "1942-1984 ",
    manufacturer: "North American ",
    capacity: 1.0,
    length: 32.25,
    wingspan: 37.0,
    wingarea: 235.0,
    aspectRatio: 5.83,
    emptyWeight: 7635.0,
    payload: 1565.0,
    mtow: 12100.0,
    maxMach: 0.58,
    serviceCeiling: 41900.0,
    range: 1434.0,
    wingLoading: 39.0,
    thrustToWeight: 0.0,
    powerplant:
      "1x Packard V-1650-7 liquid-cooled V-12, 2-stage intercooled supercharger ",
    popularVariants: "P-51D ",
    sources: "https://en.wikipedia.org/wiki/North_American_P-51_Mustang "
  },
  {
    name: "A-6 Intruder ",
    description:
      "Primarily used in Navy and has foldable wings when on the deck ",
    mission: "Attack ",
    opYears: "1963-1997 ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 2.0,
    length: 54.75,
    wingspan: 53.0,
    wingarea: 528.9,
    aspectRatio: 5.31,
    emptyWeight: 26660.0,
    payload: 13825.25,
    mtow: 60400.0,
    maxMach: 0.85,
    serviceCeiling: 42400.0,
    range: 878.0,
    wingLoading: 114.2,
    thrustToWeight: 0.31,
    powerplant: "2x Pratt & Whitney J52-P8B turbojets ",
    popularVariants: "A-6E ",
    sources: "https://en.wikipedia.org/wiki/Grumman_A-6_Intruder "
  },
  {
    name: "A-7 Corsair II ",
    description: " ",
    mission: "Attack ",
    opYears: "1965-2014 ",
    manufacturer: "Ling-Temco-Vought ",
    capacity: 1.0,
    length: 46.17,
    wingspan: 38.75,
    wingarea: 374.9,
    aspectRatio: 4.01,
    emptyWeight: 19127.0,
    payload: 12671.0,
    mtow: 41998.0,
    maxMach: 0.91,
    serviceCeiling: 42000.0,
    range: 1070.0,
    wingLoading: 77.4,
    thrustToWeight: 0.5,
    powerplant: "1x Allison TF-41-A-2 non-afterburning turbofan  ",
    popularVariants: "A-7E ",
    sources: "https://en.wikipedia.org/wiki/LTV_A-7_Corsair_II "
  },
  {
    name: "A-10 Thunderbolt II ",
    description: " ",
    mission: "Attack ",
    opYears: "1977- ",
    manufacturer: "Fairchild Republic ",
    capacity: 1.0,
    length: 53.33,
    wingspan: 57.5,
    wingarea: 506.0,
    aspectRatio: 6.53,
    emptyWeight: 24959.0,
    payload: 5425.0,
    mtow: 50000.0,
    maxMach: 0.68,
    serviceCeiling: 45000.0,
    range: 250.0,
    wingLoading: 99.0,
    thrustToWeight: 0.36,
    powerplant: "2x General Electric TF34-GE-100A turbofans ",
    popularVariants: "A-10A ",
    sources:
      "https://en.wikipedia.org/wiki/Fairchild_Republic_A-10_Thunderbolt_II "
  },
  {
    name: "A-12 Avenger II ",
    description:
      "Canceled. Intended for Navy use and had foldable wings when on the deck ",
    mission: "Attack ",
    opYears: " ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 2.0,
    length: 37.83,
    wingspan: 70.25,
    wingarea: 1308.0,
    aspectRatio: 3.77,
    emptyWeight: 39000.0,
    payload: 19678.0,
    mtow: 80000.0,
    maxMach: 0.76,
    serviceCeiling: 40000.0,
    range: 800.0,
    wingLoading: 61.0,
    thrustToWeight: 0.33,
    powerplant: "2x General Electric F412-GE-D5F2 non-afterburning turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_A-12_Avenger_II "
  },
  {
    name: "AC-47 Spooky ",
    description: " ",
    mission: "Attack ",
    opYears: "1964-1965 ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 7.0,
    length: 64.42,
    wingspan: 95.0,
    wingarea: 987.0,
    aspectRatio: 9.14,
    emptyWeight: 18080.0,
    payload: 14920.0,
    mtow: 31000.0,
    maxMach: 0.3,
    serviceCeiling: 24450.0,
    range: 1890.0,
    wingLoading: 33.4,
    thrustToWeight: 0.0,
    powerplant: "2x Pratt & Whitney R-1830 radial engines ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Douglas_AC-47_Spooky "
  },
  {
    name: "AC-130 Spectre ",
    description: " ",
    mission: "Attack ",
    opYears: "1966-2015 ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 13.0,
    length: 97.75,
    wingspan: 132.58,
    wingarea: 1745.5,
    aspectRatio: 10.07,
    emptyWeight: 75800.0,
    payload: 72000.0,
    mtow: 155000.0,
    maxMach: 0.48,
    serviceCeiling: 33000.0,
    range: 2050.0,
    wingLoading: 88.8,
    thrustToWeight: 0.0,
    powerplant: "4x Allison T56-A-15 turboprops ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_AC-130 "
  },
  {
    name: "C-1 Trader ",
    description: " ",
    mission: "Carrier ",
    opYears: "1955-1988 ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 2.0,
    length: 42.2,
    wingspan: 69.6,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 18750.0,
    payload: 10400.0,
    mtow: 29150.0,
    maxMach: 0.38,
    serviceCeiling: 0.0,
    range: 1129.67,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant:
      "2x Wright R-1820-82WA Cyclone 9-cylinder radial piston engine ",
    popularVariants: "C-1A|EC-1A|KC-2 Turbo Trader ",
    sources: "https://en.wikipedia.org/wiki/Grumman_C-1_Trader "
  },
  {
    name: "C-2 Greyhound ",
    description: " ",
    mission: "Carrier ",
    opYears: "1966- ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 38.0,
    length: 56.83,
    wingspan: 80.58,
    wingarea: 700.0,
    aspectRatio: 9.28,
    emptyWeight: 33746.0,
    payload: 20608.0,
    mtow: 60000.0,
    maxMach: 0.52,
    serviceCeiling: 33500.0,
    range: 1300.0,
    wingLoading: 77.6,
    thrustToWeight: 0.0,
    powerplant: "2x Allison T56-A-425 turboprops ",
    popularVariants: "C-2A ",
    sources: "https://en.wikipedia.org/wiki/Grumman_C-2_Greyhound "
  },
  {
    name: "C-5 Galaxy ",
    description: " ",
    mission: "Carrier ",
    opYears: "1970- ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 7.0,
    length: 247.08,
    wingspan: 222.75,
    wingarea: 6200.0,
    aspectRatio: 8.0,
    emptyWeight: 380000.0,
    payload: 285000.0,
    mtow: 920000.0,
    maxMach: 0.79,
    serviceCeiling: 41000.0,
    range: 5500.0,
    wingLoading: 120.0,
    thrustToWeight: 0.26,
    powerplant: "4x General Electric CF-6-80C2 high-bypass turbofans ",
    popularVariants: "C-5M ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_C-5_Galaxy "
  },
  {
    name: "C-17 Globemaster III ",
    description: " ",
    mission: "Carrier ",
    opYears: "1995- ",
    manufacturer: "The Boeing Company ",
    capacity: 3.0,
    length: 174.0,
    wingspan: 169.8,
    wingarea: 3800.0,
    aspectRatio: 7.59,
    emptyWeight: 282500.0,
    payload: 170900.0,
    mtow: 585000.0,
    maxMach: 0.74,
    serviceCeiling: 45000.0,
    range: 2420.0,
    wingLoading: 150.0,
    thrustToWeight: 0.28,
    powerplant: "4x Pratt & Whitney F117-PW-100 turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_C-17_Globemaster_III "
  },
  {
    name: "C-47 Skytrain ",
    description: "Developed from DC-3 ",
    mission: "Carrier ",
    opYears: "1941- ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 28.0,
    length: 63.75,
    wingspan: 95.5,
    wingarea: 987.0,
    aspectRatio: 9.24,
    emptyWeight: 18135.0,
    payload: 7865.0,
    mtow: 31000.0,
    maxMach: 0.3,
    serviceCeiling: 26400.0,
    range: 1391.0,
    wingLoading: 31.41,
    thrustToWeight: 0.0,
    powerplant:
      "2x Pratt & Whitney R-1830-90C Twin Wasp 14-cylinder radial engines ",
    popularVariants: "C-47B-DK|AC-47 Spooky ",
    sources: "https://en.wikipedia.org/wiki/Douglas_C-47_Skytrain "
  },
  {
    name: "C-74 Globemaster ",
    description: " ",
    mission: "Carrier ",
    opYears: "1945-1969 ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 125.0,
    length: 124.17,
    wingspan: 173.25,
    wingarea: 2510.0,
    aspectRatio: 11.96,
    emptyWeight: 86172.0,
    payload: 48150.0,
    mtow: 172000.0,
    maxMach: 0.43,
    serviceCeiling: 21300.0,
    range: 2950.0,
    wingLoading: 61.0,
    thrustToWeight: 0.0,
    powerplant: "4x Pratt & Whitney R-4360-69 radial engines ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Douglas_C-74_Globemaster "
  },
  {
    name: "C-124 Globemaster II ",
    description: " ",
    mission: "Carrier ",
    opYears: "1950-1974 ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 6.0,
    length: 130.42,
    wingspan: 174.13,
    wingarea: 2506.0,
    aspectRatio: 12.1,
    emptyWeight: 101165.0,
    payload: 83835.0,
    mtow: 194500.0,
    maxMach: 0.4,
    serviceCeiling: 21800.0,
    range: 6820.0,
    wingLoading: 77.61,
    thrustToWeight: 0.0,
    powerplant: "4x Pratt & Whitney R-4360-63A Wasp Major radial engines ",
    popularVariants: "C-124C ",
    sources: "NO INFO "
  },
  {
    name: "C-130 Hercules ",
    description: " ",
    mission: "Carrier ",
    opYears: "1954- ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 5.0,
    length: 97.75,
    wingspan: 132.58,
    wingarea: 1745.0,
    aspectRatio: 10.07,
    emptyWeight: 75800.0,
    payload: 72000.0,
    mtow: 155000.0,
    maxMach: 0.48,
    serviceCeiling: 33000.0,
    range: 2050.0,
    wingLoading: 88.83,
    thrustToWeight: 0.0,
    powerplant: "4x Allison T56-A-15 turboprops ",
    popularVariants: "C-130H|AC-130 ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_C-130_Hercules "
  },
  {
    name: "C-135 Stratolifter ",
    description: " ",
    mission: "Carrier ",
    opYears: "1956- ",
    manufacturer: "The Boeing Company ",
    capacity: 80.0,
    length: 136.25,
    wingspan: 130.83,
    wingarea: 2433.0,
    aspectRatio: 7.04,
    emptyWeight: 98466.0,
    payload: 198534.0,
    mtow: 322500.0,
    maxMach: 0.76,
    serviceCeiling: 50000.0,
    range: 3450.0,
    wingLoading: 132.55,
    thrustToWeight: 0.27,
    powerplant:
      "4x CFM International CFM56 high-bypass turbofans|4x Pratt & Whitney TF-33-PW-102 low-bypass turbofans ",
    popularVariants: "KC-135 ",
    sources: "https://en.wikipedia.org/wiki/Boeing_C-135_Stratolifter "
  },
  {
    name: "KC-10 Extender ",
    description: " ",
    mission: "Tanker ",
    opYears: "1981- ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 4.0,
    length: 181.58,
    wingspan: 165.38,
    wingarea: 3958.0,
    aspectRatio: 6.91,
    emptyWeight: 241027.0,
    payload: 351973.0,
    mtow: 590000.0,
    maxMach: 0.89,
    serviceCeiling: 42000.0,
    range: 3820.0,
    wingLoading: 149.07,
    thrustToWeight: 0.27,
    powerplant: "3x F103 General Electric CF6-50C2 turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_KC-10_Extender "
  },
  {
    name: "KC-46 Pegasus ",
    description: " ",
    mission: "Tanker ",
    opYears: "2019- ",
    manufacturer: "The Boeing Company ",
    capacity: 3.0,
    length: 165.5,
    wingspan: 157.67,
    wingarea: 3050.0,
    aspectRatio: 8.15,
    emptyWeight: 181610.0,
    payload: 65000.0,
    mtow: 415000.0,
    maxMach: 0.86,
    serviceCeiling: 40100.0,
    range: 6385.0,
    wingLoading: 136.07,
    thrustToWeight: 0.3,
    powerplant: "2x Pratt & Whitney PW4062 turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_KC-46_Pegasus "
  },
  {
    name: "KC-130 Hercules ",
    description: " ",
    mission: "Tanker ",
    opYears: "1962- ",
    manufacturer: "Lockheed Martin ",
    capacity: 4.0,
    length: 97.75,
    wingspan: 132.58,
    wingarea: 1745.0,
    aspectRatio: 10.07,
    emptyWeight: 75562.0,
    payload: 42000.0,
    mtow: 175000.0,
    maxMach: 0.61,
    serviceCeiling: 28000.0,
    range: 2835.0,
    wingLoading: 100.29,
    thrustToWeight: 0.0,
    powerplant: "4x Rolls-Royce AE 2100D3 turboprops ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_Martin_KC-130 "
  },
  {
    name: "KC-135 Stratotanker ",
    description: " ",
    mission: "Tanker ",
    opYears: "1956- ",
    manufacturer: "The Boeing Company ",
    capacity: 3.0,
    length: 136.25,
    wingspan: 130.83,
    wingarea: 2433.0,
    aspectRatio: 7.04,
    emptyWeight: 98466.0,
    payload: 198534.0,
    mtow: 322500.0,
    maxMach: 0.76,
    serviceCeiling: 50000.0,
    range: 3450.0,
    wingLoading: 132.55,
    thrustToWeight: 0.27,
    powerplant:
      "4x CFM International CFM56 high-bypass turbofans|4x Pratt & Whitney TF-33-PW-102 low-bypass turbofans ",
    popularVariants: " ",
    sources: " "
  },
  {
    name: "Breguet 941 ",
    description: "STOL Transport aircraft ",
    mission: "Carrier ",
    opYears: "1967-1974 ",
    manufacturer: "Breguet|McDonnell ",
    capacity: 57.0,
    length: 77.92,
    wingspan: 76.77,
    wingarea: 902.0,
    aspectRatio: 6.53,
    emptyWeight: 29610.0,
    payload: 28812.0,
    mtow: 58422.0,
    maxMach: 0.36,
    serviceCeiling: 31200.0,
    range: 540.0,
    wingLoading: 64.77,
    thrustToWeight: 0.0,
    powerplant: "4x Turbomeca Turmo IIID3 turboprop ",
    popularVariants: "McDonnell 188 ",
    sources: "https://en.wikipedia.org/wiki/Breguet_941 "
  },
  {
    name: "DC-3 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1936- ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 32.0,
    length: 64.67,
    wingspan: 95.17,
    wingarea: 987.0,
    aspectRatio: 9.17,
    emptyWeight: 16865.0,
    payload: 8334.0,
    mtow: 25199.0,
    maxMach: 0.3,
    serviceCeiling: 23200.0,
    range: 0.0,
    wingLoading: 25.5,
    thrustToWeight: 0.0,
    powerplant:
      "2x Wright R-1820 Cyclone 9-cylinder air-cooled radial piston engines|2x Pratt & Whitney R-1830-S1C3G Twin Wasp 14-cylinder air-cooled two-row radial piston engines ",
    popularVariants: "DC-3A|C-47 ",
    sources: "https://en.wikipedia.org/wiki/Douglas_DC-3 "
  },
  {
    name: "DC-10 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1971- ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 380.0,
    length: 170.5,
    wingspan: 165.33,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 270213.0,
    payload: 284787.0,
    mtow: 555000.0,
    maxMach: 0.88,
    serviceCeiling: 42000.0,
    range: 4996.61,
    wingLoading: 0.0,
    thrustToWeight: 0.29,
    powerplant: "3x Pratt & Whitney JT9D-59A high-bypass turbofans ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_DC-10 "
  },
  {
    name: "747 Dreamlifter ",
    description: "747 adapted to transport parts for the 787 Dreamliner ",
    mission: "Carrier ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "707 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1958-limited service ",
    manufacturer: "The Boeing Company ",
    capacity: 200.0,
    length: 152.92,
    wingspan: 145.75,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 148300.0,
    payload: 185300.0,
    mtow: 333600.0,
    maxMach: 0.8,
    serviceCeiling: 0.0,
    range: 5000.0,
    wingLoading: 0.0,
    thrustToWeight: 0.23,
    powerplant: "4x Pratt & Whitney JT3D turbofans ",
    popularVariants: "707-120B|707-320/-420|707-320B|707-320C ",
    sources: "https://en.wikipedia.org/wiki/Boeing_707 "
  },
  {
    name: "717 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1999- ",
    manufacturer: "The Boeing Company ",
    capacity: 117.0,
    length: 124.0,
    wingspan: 93.33,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 68500.0,
    payload: 52500.0,
    mtow: 121000.0,
    maxMach: 0.77,
    serviceCeiling: 37000.0,
    range: 2060.0,
    wingLoading: 0.0,
    thrustToWeight: 0.35,
    powerplant: "2x Rolls-Royce BR713-C1-30 ",
    popularVariants: "717-200 ",
    sources: "https://en.wikipedia.org/wiki/Boeing_717 "
  },
  {
    name: "727 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1964- ",
    manufacturer: "The Boeing Company ",
    capacity: 155.0,
    length: 153.17,
    wingspan: 108.0,
    wingarea: 1650.0,
    aspectRatio: 7.07,
    emptyWeight: 100700.0,
    payload: 108800.0,
    mtow: 209500.0,
    maxMach: 0.9,
    serviceCeiling: 36100.0,
    range: 2550.0,
    wingLoading: 126.97,
    thrustToWeight: 0.25,
    powerplant: "3x Pratt & Whitney JT8D-9/15/17/17R ",
    popularVariants: "727-100|727-200|727-200 Advanced ",
    sources: "https://en.wikipedia.org/wiki/Boeing_727 "
  },
  {
    name: "737 ",
    description: "Smallest commercial airliner jet ",
    mission: "Commercial transport ",
    opYears: "1968- ",
    manufacturer: "The Boeing Company ",
    capacity: 200.0,
    length: 138.0,
    wingspan: 117.83,
    wingarea: 1341.2,
    aspectRatio: 10.35,
    emptyWeight: 100000.0,
    payload: 100000.0,
    mtow: 200000.0,
    maxMach: 0.82,
    serviceCeiling: 41000.0,
    range: 3825.0,
    wingLoading: 149.12,
    thrustToWeight: 0.29,
    powerplant: "2x CFM International LEAP-1B ",
    popularVariants:
      "737-100|737-200|737-300/-400/-500|737-600/-700/-800/-900|737MAX ",
    sources: "https://en.wikipedia.org/wiki/Boeing_737 "
  },
  {
    name: "747 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1968- ",
    manufacturer: "The Boeing Company ",
    capacity: 467.0,
    length: 250.17,
    wingspan: 224.58,
    wingarea: 5960.0,
    aspectRatio: 8.5,
    emptyWeight: 485300.0,
    payload: 501700.0,
    mtow: 987000.0,
    maxMach: 0.9,
    serviceCeiling: 0.0,
    range: 7730.0,
    wingLoading: 165.6,
    thrustToWeight: 0.27,
    powerplant: "4x GEnx-2B67 ",
    popularVariants: "747-300|747-400ER|747-8 ",
    sources: "https://en.wikipedia.org/wiki/Boeing_747 "
  },
  {
    name: "757 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1983- ",
    manufacturer: "The Boeing Company ",
    capacity: 280.0,
    length: 178.58,
    wingspan: 124.83,
    wingarea: 1994.0,
    aspectRatio: 7.8,
    emptyWeight: 141860.0,
    payload: 131140.0,
    mtow: 273000.0,
    maxMach: 0.86,
    serviceCeiling: 42000.0,
    range: 3400.0,
    wingLoading: 136.91,
    thrustToWeight: 0.32,
    powerplant:
      "2x Rolls-Royce RB211-535E4(B)|or 2x Pratt & Whitney PW2000-37/40/43 ",
    popularVariants: "757-200/F|757-300 ",
    sources: "https://en.wikipedia.org/wiki/Boeing_757 "
  },
  {
    name: "767 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1982- ",
    manufacturer: "The Boeing Company ",
    capacity: 409.0,
    length: 201.33,
    wingspan: 170.33,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 229000.0,
    payload: 221000.0,
    mtow: 450000.0,
    maxMach: 0.85,
    serviceCeiling: 43100.0,
    range: 5625.0,
    wingLoading: 0.0,
    thrustToWeight: 0.27,
    powerplant:
      "2x General Electric CF6-80C2-B8F/C2-B7F1|or 2x Pratt & Whitney 4062 ",
    popularVariants: "767-200/ER|767-300/ER/F|767-400ER ",
    sources: "https://en.wikipedia.org/wiki/Boeing_767 "
  },
  {
    name: "777 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1995- ",
    manufacturer: "The Boeing Company ",
    capacity: 396.0,
    length: 242.33,
    wingspan: 212.58,
    wingarea: 4702.0,
    aspectRatio: 9.04,
    emptyWeight: 370000.0,
    payload: 405000.0,
    mtow: 775000.0,
    maxMach: 0.89,
    serviceCeiling: 43100.0,
    range: 7370.0,
    wingLoading: 164.82,
    thrustToWeight: 0.3,
    powerplant: "2x GE90-115B turbofans ",
    popularVariants: "777-200/ER/LR|777F|777-300/ER ",
    sources: "https://en.wikipedia.org/wiki/Boeing_777 "
  },
  {
    name: "787 Dreamliner ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "2011- ",
    manufacturer: "The Boeing Company ",
    capacity: 440.0,
    length: 224.0,
    wingspan: 197.25,
    wingarea: 4058.0,
    aspectRatio: 9.59,
    emptyWeight: 284000.0,
    payload: 276000.0,
    mtow: 560000.0,
    maxMach: 0.9,
    serviceCeiling: 43000.0,
    range: 7635.0,
    wingLoading: 138.0,
    thrustToWeight: 0.27,
    powerplant: "2x General Electric GEnx-1B|or 2x Rolls-Royce Trent 1000 ",
    popularVariants: "787-8/-9/-10 ",
    sources: "https://en.wikipedia.org/wiki/Boeing_787_Dreamliner "
  },
  {
    name: "A300 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1972-2007 ",
    manufacturer: "Airbus ",
    capacity: 345.0,
    length: 175.9,
    wingspan: 147.1,
    wingarea: 2800.0,
    aspectRatio: 7.73,
    emptyWeight: 190000.0,
    payload: 90000.0,
    mtow: 375888.0,
    maxMach: 0.82,
    serviceCeiling: 0.0,
    range: 2900.0,
    wingLoading: 134.25,
    thrustToWeight: 0.0,
    powerplant: "2x CF6-50C2|2x CF6-80C2|2x JT9D-59A|2xPW4158 ",
    popularVariants: "A300B4-200|A300-600R|A300-600F ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A300 "
  },
  {
    name: "A310 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1982- ",
    manufacturer: "Airbus ",
    capacity: 220.0,
    length: 153.08,
    wingspan: 144.0,
    wingarea: 2360.0,
    aspectRatio: 8.79,
    emptyWeight: 174500.0,
    payload: 80000.0,
    mtow: 361557.0,
    maxMach: 0.84,
    serviceCeiling: 41100.0,
    range: 5150.0,
    wingLoading: 153.2,
    thrustToWeight: 0.32,
    powerplant: "2x JT9D-7R4|2x GE CF6-80|2x Jt9D-7R4E1|2x PW4000|2x CF6-80C2 ",
    popularVariants: "A310-200|A310-300 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A310 "
  },
  {
    name: "A318 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "2002- ",
    manufacturer: "Airbus ",
    capacity: 132.0,
    length: 103.17,
    wingspan: 111.92,
    wingarea: 1318.0,
    aspectRatio: 9.5,
    emptyWeight: 87100.0,
    payload: 62900.0,
    mtow: 150000.0,
    maxMach: 0.82,
    serviceCeiling: 41000.0,
    range: 3100.0,
    wingLoading: 113.81,
    thrustToWeight: 0.32,
    powerplant: "2x CFM56-5B|2x PW6000A ",
    popularVariants: "A318-111/-112|A318-121/-122 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A318 "
  },
  {
    name: "A319 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1995- ",
    manufacturer: "Airbus ",
    capacity: 160.0,
    length: 111.0,
    wingspan: 117.42,
    wingarea: 1318.0,
    aspectRatio: 10.46,
    emptyWeight: 90000.0,
    payload: 76000.0,
    mtow: 166000.0,
    maxMach: 0.82,
    serviceCeiling: 41000.0,
    range: 3700.0,
    wingLoading: 125.95,
    thrustToWeight: 0.33,
    powerplant: "2x CFM56-5B|2x IAE V2500A5 ",
    popularVariants: "A319-111 thru -115|A319-131 thru -133 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A319 "
  },
  {
    name: "A320 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1987- ",
    manufacturer: "Airbus ",
    capacity: 195.0,
    length: 123.25,
    wingspan: 117.42,
    wingarea: 1330.0,
    aspectRatio: 10.37,
    emptyWeight: 93900.0,
    payload: 78100.0,
    mtow: 172000.0,
    maxMach: 0.82,
    serviceCeiling: 41000.0,
    range: 3300.0,
    wingLoading: 129.32,
    thrustToWeight: 0.31,
    powerplant: "2x CFM56-5B|2x IAE V2500A5 ",
    popularVariants: "A320-111|A320-211 thru -216|A320-231 thru -233 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A320_family "
  },
  {
    name: "A321 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1993- ",
    manufacturer: "Airbus ",
    capacity: 230.0,
    length: 146.0,
    wingspan: 117.42,
    wingarea: 1380.0,
    aspectRatio: 9.99,
    emptyWeight: 107000.0,
    payload: 99000.0,
    mtow: 206000.0,
    maxMach: 0.82,
    serviceCeiling: 41000.0,
    range: 3200.0,
    wingLoading: 149.28,
    thrustToWeight: 0.32,
    powerplant: "2x CFM56-5B|2x IAE V2500A5 ",
    popularVariants: "A321-111/-112|A321-131|A321-211 thru -213|A321-231/-232 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A321 "
  },
  {
    name: "A330 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1992- ",
    manufacturer: "Airbus ",
    capacity: 440.0,
    length: 208.89,
    wingspan: 197.83,
    wingarea: 3892.0,
    aspectRatio: 10.06,
    emptyWeight: 270675.0,
    payload: 262844.0,
    mtow: 533519.0,
    maxMach: 0.86,
    serviceCeiling: 41100.0,
    range: 6350.0,
    wingLoading: 137.08,
    thrustToWeight: 0.26,
    powerplant:
      "2x General Electric CF6-80E1|2x Pratt & Whitney PW 4000 series|Rolls-Royce Trent 700 series ",
    popularVariants: "A330-200/-200F/-300 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A330 "
  },
  {
    name: "A340 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "1991- ",
    manufacturer: "Airbus ",
    capacity: 326.0,
    length: 247.25,
    wingspan: 208.17,
    wingarea: 4707.0,
    aspectRatio: 9.21,
    emptyWeight: 390000.0,
    payload: 194000.0,
    mtow: 584000.0,
    maxMach: 0.82,
    serviceCeiling: 41100.0,
    range: 7800.0,
    wingLoading: 124.07,
    thrustToWeight: 0.42,
    powerplant: "4x CFM International CFM56-5C|4x Rolls-Royce Trent 500 ",
    popularVariants: "A340-200|A340-300|A340-500|A340-600 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A340 "
  },
  {
    name: "A350 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "2013- ",
    manufacturer: "Airbus ",
    capacity: 387.0,
    length: 242.7,
    wingspan: 212.43,
    wingarea: 5000.0,
    aspectRatio: 9.12,
    emptyWeight: 342000.0,
    payload: 343638.0,
    mtow: 685638.0,
    maxMach: 0.89,
    serviceCeiling: 41450.0,
    range: 7950.0,
    wingLoading: 137.13,
    thrustToWeight: 0.28,
    powerplant: "2x Rolls-Royce Trent XWB ",
    popularVariants: "A350-900|A350-1000 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A350_XWB "
  },
  {
    name: "A380 ",
    description: " ",
    mission: "Commercial transport ",
    opYears: "2005- ",
    manufacturer: "Airbus ",
    capacity: 544.0,
    length: 238.58,
    wingspan: 261.67,
    wingarea: 9100.0,
    aspectRatio: 7.53,
    emptyWeight: 610000.0,
    payload: 658000.0,
    mtow: 1268000.0,
    maxMach: 0.89,
    serviceCeiling: 43000.0,
    range: 8200.0,
    wingLoading: 139.34,
    thrustToWeight: 0.22,
    powerplant: "4x Engine Alliance GP7200|Rolls-Royce Trent 900 ",
    popularVariants: "A380-841/-842|A380-861 ",
    sources: "https://en.wikipedia.org/wiki/Airbus_A380 "
  },
  {
    name: "X-1 ",
    description: "To break the sound barrier ",
    mission: "Experimental ",
    opYears: "1946 ",
    manufacturer: "Bell ",
    capacity: 1.0,
    length: 31.0,
    wingspan: 22.83,
    wingarea: 115.0,
    aspectRatio: 4.53,
    emptyWeight: 6850.0,
    payload: 7900.0,
    mtow: 14750.0,
    maxMach: 2.24,
    serviceCeiling: 90000.0,
    range: 0.0,
    wingLoading: 128.26,
    thrustToWeight: 0.41,
    powerplant: "1x Reaction Motors RMI LR-8-RM-5 rocket ",
    popularVariants: "X-1E ",
    sources: "https://en.wikipedia.org/wiki/Bell_X-1 "
  },
  {
    name: "X-2 ",
    description:
      "Investigate flight characteristics in Mach 2-3 range. Expand the speend and altitude regines obtained with X-1 series. Dropped from B-50 at subaltitude for launch ",
    mission: "Experimental ",
    opYears: "1952-1956 ",
    manufacturer: "Bell ",
    capacity: 1.0,
    length: 37.83,
    wingspan: 32.25,
    wingarea: 260.0,
    aspectRatio: 4.0,
    emptyWeight: 12375.0,
    payload: 12535.0,
    mtow: 24910.0,
    maxMach: 3.2,
    serviceCeiling: 126200.0,
    range: 0.0,
    wingLoading: 95.81,
    thrustToWeight: 0.6,
    powerplant: "1x Curtiss-Wright XLR25 rocket engine ",
    popularVariants: "Starbuster ",
    sources: "https://en.wikipedia.org/wiki/Bell_X-2 "
  },
  {
    name: "X-3 Stiletto ",
    description: " ",
    mission: "Experimental ",
    opYears: "1952-1957 ",
    manufacturer: "Douglas|The Boeing Company ",
    capacity: 1.0,
    length: 66.75,
    wingspan: 22.67,
    wingarea: 166.5,
    aspectRatio: 3.09,
    emptyWeight: 16120.0,
    payload: 7720.0,
    mtow: 23840.0,
    maxMach: 0.92,
    serviceCeiling: 38000.0,
    range: 431.88,
    wingLoading: 143.18,
    thrustToWeight: 0.4,
    powerplant: "2x Westinghouse J34 afterburning turbojet ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Douglas_X-3_Stiletto "
  },
  {
    name: "X-4 Bantam ",
    description:
      "The idea was proposed that eliminating the horizontal tail would do away with stability problems at fast speeds (shock stall) resulting from the interaction of supersonic shock waves from the wings and the horizontal stabilizers. The flight control systems of the time prevented its success. Bantam still had a vertical tail for yaw stability ",
    mission: "Experimental ",
    opYears: "1948 ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 1.0,
    length: 22.25,
    wingspan: 26.83,
    wingarea: 200.0,
    aspectRatio: 3.6,
    emptyWeight: 5507.0,
    payload: 2313.0,
    mtow: 7820.0,
    maxMach: 0.82,
    serviceCeiling: 42300.0,
    range: 365.0,
    wingLoading: 39.1,
    thrustToWeight: 0.41,
    powerplant: "2x Westinghouse J30-WE-7/9 turbojet ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Northrop_X-4_Bantam "
  },
  {
    name: "X-5 ",
    description:
      "Fighter with variable sweep to accommodate different flight profiles and missions.|The spread configuration has a 33.5 ft wingspan ",
    mission: "Experimental ",
    opYears: "1951-1958 ",
    manufacturer: "Bell ",
    capacity: 1.0,
    length: 33.33,
    wingspan: 20.83,
    wingarea: 175.0,
    aspectRatio: 2.48,
    emptyWeight: 6336.0,
    payload: 3644.0,
    mtow: 9980.0,
    maxMach: 0.94,
    serviceCeiling: 49900.0,
    range: 651.73,
    wingLoading: 57.03,
    thrustToWeight: 0.5,
    powerplant: "1x Allison J35-A-17 turbojet ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Bell_X-5 "
  },
  {
    name: "X-6 ",
    description: "Experimental bomber based off of Convair B-36 ",
    mission: "Experimental ",
    opYears: "Canceled ",
    manufacturer: "Convair ",
    capacity: 5.0,
    length: 162.08,
    wingspan: 230.0,
    wingarea: 4772.0,
    aspectRatio: 11.09,
    emptyWeight: 166165.0,
    payload: 96335.0,
    mtow: 360000.0,
    maxMach: 0.51,
    serviceCeiling: 40000.0,
    range: 0.0,
    wingLoading: 75.44,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "https://en.wikipedia.org/wiki/Convair_X-6 "
  },
  {
    name: "X-7 ",
    description: " ",
    mission: "Experimental ",
    opYears: "1951-1960 ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 0.0,
    length: 37.0,
    wingspan: 10.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 8000.0,
    maxMach: 3.0,
    serviceCeiling: 100000.0,
    range: 113.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "2x Thiokol XM45 solid-fuel rocket, ramjet sustainer ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Lockheed_X-7 "
  },
  {
    name: "X-8 Aerobee ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Aerojet ",
    capacity: 0.0,
    length: 20.13,
    wingspan: 5.25,
    wingarea: 36.0,
    aspectRatio: 0.77,
    emptyWeight: 135.0,
    payload: 300.0,
    mtow: 1097.0,
    maxMach: 5.28,
    serviceCeiling: 800000.0,
    range: 18.0,
    wingLoading: 30.47,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "https://en.wikipedia.org/wiki/Aerojet_General_X-8 "
  },
  {
    name: "X-9 Shrike ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Bell ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-10 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "North American ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-11 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Convair ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-12 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Convair ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-13 Vertijet ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Ryan ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-14 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Bell ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-15 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "North American ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-16 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Bell ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-17 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-18 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Hiller ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-19 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Curtiss-Wright ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-20 Dyna-Soar ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-21 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Northrop|Northrop Grumman ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-22 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Bell ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-23 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Martin Marietta ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-24 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Martin Marietta ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-25 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Bensen ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-26 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Schweizer ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-27 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed|Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-28  ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Osprey ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-29 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Grumman|Northrop Grumman ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-30 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Rockwell|The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-31 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Rockwell|Messerschmitt-Bölkow-Blohm|The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-32 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-33 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-34 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Orbital Sciences ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-35 ",
    description: "Became F-35 ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-36 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "McDonnell Douglas|The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-37 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-38 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Scaled Composites ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-39 ",
    description:
      "Future Aircraft Technology Enhancements (FATE) program. Run by Air Force Research Laboratory (AFRL) and Defense Advanced Research Projects Agency (DARPA) ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Unknown ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "Unknown ",
    popularVariants: "Unknown ",
    sources: "NO INFO "
  },
  {
    name: "X-40 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-41 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Unknown ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-42 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Unknown ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-43 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Micro Craft ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-44 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-45 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-46 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-47 Pegasus ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Northrop Grumman ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-48 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-49 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Piasecki ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-50 Dragonfly ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-51 Waverider ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-53 ",
    description:
      "Developed from F-18 for aeroelastic tailoring at high dynamic pressures ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "The Boeing Company ",
    capacity: 2.0,
    length: 56.08,
    wingspan: 40.33,
    wingarea: 410.0,
    aspectRatio: 4.0,
    emptyWeight: 23000.0,
    payload: 13970.0,
    mtow: 51900.0,
    maxMach: 1.8,
    serviceCeiling: 50000.0,
    range: 1089.0,
    wingLoading: 93.0,
    thrustToWeight: 0.96,
    powerplant: "2x General Electric F404-GE-402 afterburning turbofans ",
    popularVariants: "F/A-18 ",
    sources: "https://en.wikipedia.org/wiki/McDonnell_Douglas_F/A-18_Hornet "
  },
  {
    name: "X-54 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Gulfstream ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "2x Rolls-Royce Tay 651 ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-55 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-56 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "Lockheed Martin ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "X-57 ",
    description: " ",
    mission: "Experimental ",
    opYears: " ",
    manufacturer: "ESAero|Tecnam ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 0.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 0.0,
    payload: 0.0,
    mtow: 0.0,
    maxMach: 0.0,
    serviceCeiling: 0.0,
    range: 0.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant: "NO INFO ",
    popularVariants: "NO INFO ",
    sources: "NO INFO "
  },
  {
    name: "Phantom Eye ",
    description: " ",
    mission: "Experimental|Reconnaissance|HALE ",
    opYears: "2012 ",
    manufacturer: "The Boeing Company ",
    capacity: 0.0,
    length: 0.0,
    wingspan: 150.0,
    wingarea: 0.0,
    aspectRatio: 0.0,
    emptyWeight: 6800.0,
    payload: 450.0,
    mtow: 7250.0,
    maxMach: 0.3,
    serviceCeiling: 65000.0,
    range: 14400.0,
    wingLoading: 0.0,
    thrustToWeight: 0.0,
    powerplant:
      "2x modified Ford 2.3L engine, reduction gear box|2x 4-blade propellers ",
    popularVariants: " ",
    sources: "https://en.wikipedia.org/wiki/Boeing_Phantom_Eye "
  },
  {
    name: " ",
    description: " ",
    mission: " ",
    opYears: " ",
    manufacturer: " ",
    capacity: NaN,
    length: NaN,
    wingspan: NaN,
    wingarea: NaN,
    aspectRatio: NaN,
    emptyWeight: NaN,
    payload: NaN,
    mtow: NaN,
    maxMach: NaN,
    serviceCeiling: NaN,
    range: NaN,
    wingLoading: NaN,
    thrustToWeight: NaN,
    powerplant: " ",
    popularVariants: " ",
    sources: " "
  }
];

/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/
